//Products actions
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'
export const PURCHASE_ITEM = "PURCHASE_ITEM";
export const ARCHIVE_ITEM = "ARCHIVE_ITEM";
export const REACTIVE_ITEM = "REACTIVE_ITEM";

//Currency actions
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_ERROR = "FETCH_CURRENCY_ERROR";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
